### ISSUE TITLE
I found a bug., survey row 85

### ISSUE THREAD

**Issue by plocket** [SuffolkLITLab/docassemble-MAVirtualCourt#254] opened 2020-05-20 01:59 UTC
# Survey result on row 85

**Report type:** I found a bug.

---

### Bug

Question | Answer
---|---
**Question** | Defendant’s Insurance Expenses
**Actions** | I seemingly finished the interview, got to the signature page and it looped me back to this insurance page. 
**Expected** | There is no error report or reason for me being back to this screen. I assumed after I signed the signature I would get to some ending spot, perhaps a review of the prior answers. 
**Actual** | After signing the signature, I got looped back to the defendant insurance screen. There doesn't seem to be any way "out". There's no reported error or absence of information. I just cannot get off the screen and I don't know why I've been sent back here in the first place, since this was filled out with the child support information earlier on. This error has replicated in two different iterations of my filling out the interview. I tried changing information and it still doesn't let me off the screen so I simply have to quit and then I don't get to complete the form. This is after filling out the form for about 30-40 minutes and getting no product at the end
**Feedback** | 

---

### Confusion feedback

Question | Answer
---|---
**Question** | 
**Confusion** | 
**Feedback** | 

---

### Something else

Uncategorized Feedback:

---

### Test report

Question | Answer
---|---
**Link to spreadsheet** | 
**Test id** | 
**Tester** | 
**Question** | 
**Input** | 
**Expected** | 
**Actual** | 
**Link** | 
**Pic** | 
**Notes** | 

**Error message**
```

```

---

### Thank you!

**Comment by nonprofittechy** [comment] 2020-05-20 13:34
Duplicate of #228

**Closed as completed by nonprofittechy** 2020-05-20 13:34 UTC
Labels: duplicate
