### ISSUE TITLE
Internal: A test case (qa), row 97

### ISSUE THREAD

**Issue by plocket** [SuffolkLITLab/docassemble-MAVirtualCourt#455] opened 2020-07-01 13:25 UTC
# Survey result on row 97

**Report type:** A test case (qa)

**Contact info**: Sinéad Vaughan - Test 1.8 

---

### Bug

Question | Answer
---|---
**Question** | 
**Actions** | 
**Expected** | 
**Actual** | 
**Feedback** | 

---

### Confusion feedback

Question | Answer
---|---
**Question** | 
**Confusion** | 
**Feedback** | 

---

### Something else

Uncategorized Feedback:

---

### Test report

Question | Answer
---|---
**Link to spreadsheet** | https://apps-dev.suffolklitlab.org/uploadedfile/9110/file.pdf
**Test id** | 209A, Case 1.18 - Interview Row: 22
**Tester** | sineadvaughan
**Question** | 1st Issue - Describe the Incident - Title Screen
**Input** | 1st Issue - Question was not one that was being tested in the scenario.
2nd Issue - "Enter A LOT of text in the 'What visitation center?' field (we want to see what happens if an excessive amount of text is entered into this field and how it shows up on the pdf form)" - Row 22 Cell AF.
**Expected** | 1st Issue - Expected to have full information in line "last summer, 2008".
2nd Issue - Expected to have full information about the visitation.
**Actual** | 1st Issue - The '8' in 2008 is not showing up.
2nd Issue - Only half of the information is showing up. 
**Link** | 
**Pic** | https://drive.google.com/open?id=1EiyjK0Kyv3oGNx6u0w8YcS8_EyzXHnnq, https://drive.google.com/open?id=1oAc0g1o338-YhkP6sdtVVq5fr-yDIUQo, https://drive.google.com/open?id=1pf4v1Alj8RG7EqNn0I1CDvFXhFjIuaUb
**Notes** | 

**Error message**
```

```

---

### Thank you!

**Comment by nonprofittechy** [comment] 2020-07-01 14:36
Duplicate of #457

**Closed as completed by nonprofittechy** 2020-07-01 14:36 UTC
Labels: duplicate
