### ISSUE TITLE
209A: Plaintiff Confidential Information - Make field optional

### ISSUE THREAD

**Issue by plocket** [SuffolkLITLab/docassemble-MAVirtualCourt#126] opened 2020-05-06 16:24 UTC
# Survey result on row 52

**Report type:** Part of the form was confusing.

---

### Bug

Question | Answer
---|---
**Question** | 
**Actions** | 
**Expected** | 
**Actual** | 
**Feedback** | 

---

### Confusion feedback

Question | Answer
---|---
**Question** | Former or Prior Address (plaintiff confidential information form)
**Confusion** | It had a mandatory "location" field and I'm not sure what that was meant to be since it also asked for address
**Feedback** | this is kate 

---

### Something else

Uncategorized Feedback:

---

### Test report

Question | Answer
---|---
**Link to spreadsheet**: | 
**Test id** | 
**Tester** | 
**Input** | 
**Expected** | 
**Actual** | 
**Link** | 
**Pic** | 
**Notes** | 

**Error message**
```

```

---

### Thank you!

**Comment by nonprofittechy** [comment] 2020-05-07 00:19
I couldn't figure out what field this was. Do you have any more info?

**Comment by nonprofittechy** [comment] 2020-05-14 15:27
Closing for lack of info. I think this must have been caused by an old version of the form that's no longer present. The word "location" isn't in the current YAML files

**Closed as completed by nonprofittechy** 2020-05-14 15:27 UTC
Labels: bug
