### ISSUE TITLE
209A Test Case 1.4 and 1.5: Superior Court an option when "dating"

### ISSUE THREAD

**Issue by kateleebarry** [SuffolkLITLab/docassemble-MAVirtualCourt#448] opened 2020-06-30 15:45 UTC
This is test case 1.4.  The tester selected "used to date" as sole relationship and also selected Superior Court as venue even though Superior Court should not be an option if dating/used to date is sole basis for relationship.  

https://drive.google.com/file/d/1c5FwdcBRP8LmYe6SB9hvcY_CIcb-YIze/view?usp=sharing

Also 1.5, selected "currently dating" as well as superior court.

**Comment by nonprofittechy** [comment] 2020-07-01 02:57
Duplicate of #176

**Closed as completed by nonprofittechy** 2020-07-01 02:57 UTC
Labels: duplicate
