### ISSUE TITLE
TRO: Relief should require an answer

### ISSUE THREAD

**Issue by plocket** [SuffolkLITLab/docassemble-MAVirtualCourt#150] opened 2020-05-07 16:27 UTC
# Survey result on row 62

**Report type:** I'd like to describe a test case.

---

### Bug

Question | Answer
---|---
**Question** | 
**Actions** | 
**Expected** | 
**Actual** | 
**Feedback** | 

---

### Confusion feedback

Question | Answer
---|---
**Question** | 
**Confusion** | 
**Feedback** | 

---

### Something else

Uncategorized Feedback:

---

### Test report

Question | Answer
---|---
**Link to spreadsheet** | https://docs.google.com/spreadsheets/d/1RE28nqXnAloroO2aRDnydpimRI_PPLc2V42Yp937zw0/edit#gid=1780719876
**Test id** | 13
**Tester** | Lance Godard
**Question** | What are you asking the court to do?'
**Input** | Unselect pre-selected option / Uncheck 'Let me back into the apartment' / then Click Continue
**Expected** | Pop up indicating user must select a relief option should appear
**Actual** | Allowed to continue to next question without selecting relief
**Link** | What are you asking the court to do?'
**Pic** | 
**Notes** | Here's the link for the relief question. Unchecking all three boxes then clicking continue should produce same error. https://apps-dev.suffolklitlab.org/interview?i=docassemble.playground12TROtesting%3AHousing_Temporary_Restraining_Order.yml&session=S6PzDTwxLxFjnAd3dDCvst2IjGcuEL1X

**Error message**
```

```

---

### Thank you!

**Comment by nonprofittechy** [comment] 2020-05-07 20:28
Duplicate of #149

**Closed as completed by nonprofittechy** 2020-05-07 20:28 UTC
Labels: duplicate
