### ISSUE TITLE
I'd like to describe a test case., survey row 71

### ISSUE THREAD

**Issue by plocket** [SuffolkLITLab/docassemble-MAVirtualCourt#184] opened 2020-05-14 14:30 UTC
# Survey result on row 71

**Report type:** I'd like to describe a test case.

---

### Bug

Question | Answer
---|---
**Question** | 
**Actions** | 
**Expected** | 
**Actual** | 
**Feedback** | 

---

### Confusion feedback

Question | Answer
---|---
**Question** | 
**Confusion** | 
**Feedback** | 

---

### Something else

Uncategorized Feedback:

---

### Test report

Question | Answer
---|---
**Link to spreadsheet** | https://docs.google.com/spreadsheets/d/16YJCxSb8KsM_nQPuhNbt1wrMZ_7T3-sdhB5xvFQb3CM/edit#gid=0
**Test id** | 209A Impoundment, Case 03A - Interview row: 21
**Tester** | RobynCasper
**Question** | PDF Preview
**Input** | Clicked on the PDF that was generated 
**Expected** | PDF opened in a new tab
**Actual** | Under question #2 on the PDF, the box in the corner stating "If more space is needed, attach additional pages and check this box" is checked off without my prompting
**Link** | 
**Pic** | https://drive.google.com/open?id=1SWluG2mFPOvBcJvMlNJXfksoec_uWNcu
**Notes** | 

**Error message**
```

```

---

### Thank you!

**Comment by nonprofittechy** [comment] 2020-05-14 15:20
duplicate of #182

**Closed as completed by nonprofittechy** 2020-05-14 15:20 UTC
Labels: duplicate
