### ISSUE TITLE
209a: sometimes pdf image on screen is blank

### ISSUE THREAD

**Issue by jodicantrell** [SuffolkLITLab/docassemble-MAVirtualCourt#410] opened 2020-06-22 17:50 UTC
When getting to final screen where pdf is "finished" - sometimes the box is blank (this has happened to me on a Mac in both Chrome and in Safari).  Rather than trying to troubleshoot what is making it show up blank, can we just put some kind of a [watermark?] over the box itself that says "click here", so if it does show up blank, it won't confuse/deter anyone from clicking the box and getting their pdf? (see example of box being blank) 

<img width="563" alt="image" src="https://user-images.githubusercontent.com/66283360/85319097-ef77ca80-b475-11ea-8403-4b27b4417b1e.png">

**Comment by nonprofittechy** [comment] 2020-06-22 17:53
Duplicate of #298

**Closed as completed by nonprofittechy** 2020-06-22 17:53 UTC
Labels: duplicate
