### ISSUE TITLE
209A: Affidavit of Care: Ambiguous word "paternity"

### ISSUE THREAD

**Issue by kateleebarry** [SuffolkLITLab/docassemble-MAVirtualCourt#230] opened 2020-05-18 21:24 UTC
The word "paternity" in the case-type drop down menu should be changed to "action to establish paternity" to avoid ambiguity.  

Copied from Slack:
My other concern is with listing "paternity" as a choice.  That wording should be changed to "complaint to establish paternity" or "action to establish paternity."  The word "paternity" alone (as in "I filed a paternity" or "I have a current paternity case") in reference to a family law action is typically used to refer to any action between unmarried parents related to their children, such as custody and parenting time cases.  Complaint Page 2 seems to be asking about cases to "establish paternity."  Simply putting the word "paternity" as an option will not be clear to users who have had interactions with the probate court system and will have heard court staff, lawyers, judges, etc., referring to any custody case between unmarried as a "paternity."

**Comment by nonprofittechy** [comment] 2020-05-20 12:38
Duplicate of #247

**Closed as completed by nonprofittechy** 2020-05-20 12:38 UTC
Labels: duplicate
