### ISSUE TITLE
Difficult mobile interaction for address entry

### ISSUE THREAD

**Issue by plocket** [SuffolkLITLab/docassemble-MAVirtualCourt#155] opened 2020-05-08 19:55 UTC
# Survey result on row 64

**Report type:** I'd like to describe a test case.

Duplicate of #123, but with more details.

---

### Bug

Question | Answer
---|---
**Question** | 
**Actions** | 
**Expected** | 
**Actual** | 
**Feedback** | 

---

### Confusion feedback

Question | Answer
---|---
**Question** | 
**Confusion** | 
**Feedback** | 

---

### Something else

Uncategorized Feedback:

---

### Test report

Question | Answer
---|---
**Link to spreadsheet** | https://docs.google.com/spreadsheets/d/1S6AmYzen4ldAd36axHVitQBkIW23kJFwD3JGRrP7vDE/edit#gid=0
**Test id** | Housing TRO, Case 1 - Interview row: 16
**Tester** | John McConchie
**Question** | What is your contact information?'
**Input** | I typed in the address "47 Aspen Court" into a text box called "Street Address"
**Expected** | The expected behavior was that the words "47 Aspen Court" would appear.
**Actual** | The unexpected behavior was that after the words "47 Aspen Court" were typed, there was no clear and obvious path for the user to proceed.  The most natural path, by clicking an "Enter" key or equivalent, caused the words "47 Aspen Court" to disappear and red reminders to appear.  A detailed explanation follows:

The unexpected behavior was that after the words "47 Aspen Court" were typed, there was no clear and obvious path for the user to proceed.  The most natural path, by clicking an "Enter" key or equivalent, caused the words "47 Aspen Court" to disappear and red reminders to appear.  A detailed explanation follows:

The error that arose in my testing of the Housing TRO interview may demonstrate that where a user does the interview on an iPad, we may need to make certain adjustments to ensure a good user experience.  This may even be true in connection with the desktop users.

The user interview at Housing TRO, Case 1 - Interview row: 16 is intended to collect the user’s contact information. It provides an array of input boxes for address particulars stretching one after another from the top-most field to the bottom of the page. The top-most control provides the input for the ‘Street Address’. In the interview, the user is asked to type in the Street Address. This obviously requires the user to click in the ‘Street Address’ input box.  As soon as the user does this, the input box reveals itself to be a dropdown combo box control.  It unfolds directly over the input boxes for the ‘Unit’ description, ‘City’, and ‘State’ controls, hiding all of those input text boxes (but not the labels) until it comes to an end just above the ‘Zip’ input box.  If the user is doing the interview on an iPad (it should also be tested on an iPhone), the user will have been typing out the Street Address on a virtual keyboard. The virtual keyboard, unlike the keyboard used with the desktops, is activated by the typing  and rises up to cover the bottom half of the screen.  Even without this additional “blinding” effect of the virtual screen on the user’s possible pathways to completion of the address particulars, the fact is that the input controls for the ensuing address controls are now fully covered and therefore inaccessible to the user without the user taking some non-guided action to access them. I think that the desktop user might instinctively know to click outside the ‘Street Address’ input field if none of its entries are selected once the user completes the Street Address. But an iPad user in that situation will, I believe, become attracted as I did to the solution presented by the virtual keyboard. That keyboard has a “go” button in the place of the usual Enter key. At this point, everything about the presentation on the screen tells the user intuitively to click the “go” button so as to clear the virtual keyboard and open up access to the next set of controls.

When I did just that in testing the interview question, the virtual keyboard did, in fact, disappear but this was accompanied by the simultaneous disappearance of the text I had typed into the ‘Street Address’ input box. I was left with an empty Street Address box and three red error-type messages reminding me that I must fill in the Street Address field, the City field and one or two others that were marked with red asterisks (see the screen grab below).

Based on my test of this situation using a desktop computer as a follow-up to the iPad, I think that the user of a normal desktop computer with mechanical keyboard might still need a bit of guidance getting around the covering effect of the Dropdown list, but I may be not giving the user their full due. However, I think an iPad user would be likely to trigger the errors that I have mentioned.

The result of this is that I would recommend that the developers consider how to eliminate the problem caused by the cascade of events on the iPad following entry of text into the Street Address field.  Depending on available screen-size, our exceptional JavaScript people could likely cure this with a Dropbox-right or even Dropbox-up variation/effect (the Dropbox on the subject page actually begins with the unfurling taking place up and away from the control but sudden becomes a Dropbox-down when the words are typed in the input box).  In short, the problem is likely fixed when the Dropbox does not drop its list straight down from the first input box.

Below is a screenshot of the screen cover provided by the drop-down Street Address control and the iPad virtual keyboard just after the user has typed text into the Street Address input box ("coverage.png"), and to its right is a shot of the “error” type messages which remain after the screen has erased the user’s text from the Street Address control and invited the user to fill in the mandatory input boxes ("error_messages.png").

**Link** | What is your contact information?'
**Pic** | https://drive.google.com/open?id=1PqcFFRFDXnWVauDYPWgIGYVAzqCXv43o, https://drive.google.com/open?id=1VThaweYZghSO9vy6UlWEvl2jwbqnYdhB
**Notes** | On this report page there is a request for the link to the actual interview page.  This is secured by a right click on a certain link on that page.  All of that is fine.  However, the question comes when you are in the course of completing the report.  I am sure there are many fixes to this but I expect that others like me will try to back out of the report we are mostly finished with and get the link, come back in an paste it.  No such luck.  The data is not saved.  If you are lucky enough to get the link before entering the report location, and not overwriting it with any other information (if you are just using the clipboard), then you might survive.  Otherwise, you may lose all your information and have to start again, making sure that you get a copy of the link address and pop it into the report as soon as possible.

**Error message**
```
See above.  They were not so much error messages in themselves but reminders to the user as to which were the mandatory fields.  The fact is that they only arose because the user made an error (or at least that is the implication).
```

---

### Thank you!

**Comment by nonprofittechy** [comment] 2020-05-09 01:43
Duplicate of #123 (although this gives more info)

**Closed as completed by nonprofittechy** 2020-05-09 01:43 UTC
Labels: duplicate
