### ISSUE TITLE
209A: Child Protection Screening question--turn into interstititial screen and remove yes/no buttons

### ISSUE THREAD

**Issue by kateleebarry** [SuffolkLITLab/docassemble-MAVirtualCourt#423] opened 2020-06-24 16:42 UTC
I think we may want to separate child support from this question.  Child support doesn't intuitively seem like something everyone will think of as "protecting" the children, so I'm worried people will say no here, without realizing they are going to be skipping the option to get child support later.  Maybe everyone with children should be asked about CS regardless of what they say here. 

![image](https://user-images.githubusercontent.com/63356951/85596647-e888bd80-b617-11ea-9b70-83a1fde00971.png)

**Comment by CaroRob** [comment] 2020-06-24 21:05
My **plan** was to have it skip requests for relief if they say no, but right now it doesn't skip - never got around to it,  so people still get asked all the relief questions anyway, even if they say they do not need to include them. 

Note: we do have "Order Kate to pay child support for the children," in this list, but point taken everyone may not read everything on the list, so - maybe we should skip change the language in the Question and not ask Yes No  just have a Next button?

**Comment by nonprofittechy** [comment] 2020-07-01 03:45
Duplicate of #451

**Closed as completed** 2020-07-10 15:04 UTC
