### ISSUE TITLE
TRO: Play bar not working (on any interview)

### ISSUE THREAD

**Issue by plocket** [SuffolkLITLab/docassemble-MAVirtualCourt#202] opened 2020-05-15 18:44 UTC
This is on the master branch and stitchup. Probably an upstream problem, but we may have to remove the play bar if it isn't working.

* Macbook Pro 10.11
* Chrome 81.0
* Incognito or regular browser

Pressed play and this shows up and stays how you see it in the image. Let it go for a couple mins. to make sure:
<img width="578" alt="Screen Shot 2020-05-15 at 2 26 04 PM" src="https://user-images.githubusercontent.com/52798256/82084873-0dede780-96ba-11ea-8541-b20ea5268b0a.png">

---
Reproduced:
* master branch
* iphone 11 pro max 13.3
* safari v13
> For me nothing happens. I click play and the “Error” shows up on the bar. Timestamps don't show up on my device. It just says 0:00.

**Comment by plocket** [comment] 2020-05-15 18:55
It worked for two people with this environment:
* Dell Laptop with Windows 10, running Chrome Version 81.0.4044.138

**Comment by plocket** [comment] 2020-05-15 18:55
Works for this too:
* Macbook Air 10.15.5, Chrome v80
* Macbook Pro 10.11, Firefox

**Comment by plocket** [comment] 2020-05-15 19:05
Reproduced, though on an old device:
* iPhone 10.1.1
* Safari 10

Play button appears in a gray bar with nothing in it. Pressing play makes the triangle light up, but that's all.

I will put further reproductions here:
* iPad iOS 12.4.6; Safari is 12.1 has 'error' in a proper Safari window and through Slack
* iPadOS 13.4.1, Safari 13.

Wish I could get other devices on here to figure out whether a 'majority' of devices are affected.

**Comment by nonprofittechy** [comment] 2020-05-15 19:16
What would be helpful is to know if there are any javascript errors or log messages that appear in docassemble's log when this is going on. The "play bar" is just an HTML audio element that plays a file downloaded via API. Do other HTML audio elements work on these devices? Did we reach an API limit because a bunch of people were testing many different screens? The above information is not enough to do any useful troubleshooting especially as I don't know where to look in the log at what time or have access to these devices to replicate the issue.

Unless this affects a majority of devices I don't think we should remove it.

**Comment by plocket** [comment] 2020-05-15 19:26
The time is within the past hour. In my browser on my desktop I didn't see any console messages. Trying to figure out which log to look at.

Not sure where to find other HTML audio elements to try.

**Comment by plocket** [comment] 2020-05-15 19:27
Also, how do we know how many devices this works on?

**Comment by plocket** [comment] 2020-05-15 19:33
The browser versions reported are supposed to work with audio elements: https://caniuse.com/#feat=audio

**Comment by nonprofittechy** [comment] 2020-05-15 19:36
It may be useful to start a chat with Jonathan on Slack about it, but a log message would be very helpful for that.

Does it always fail on certain devices? If it fails on one device, does it fail at the same time on a device it previously worked on? Trying to narrow down to API issues vs browser incompatibility vs a server configuration problem.

Another good way to test may be to use gbls.org/MADE on a device that doesn't work on our TRO. It could end up being a CSS problem or something caused by custom JS we have.

I don't see this as a high enough priority to disable until it's fixed though unless we find out it doesn't work for most people. I also don't want to take away time from the other things I'm working on to do track down this issue that only appears on devices I don't have access to (if we can confirm that's the issue and not that the voicerss API is falling down at specific times, a file space issue, etc). 

I can help troubleshoot it when we're in phase 2. I think better to have it available to the people who need it. It's not just a nicety, it's crucial for people who don't read well.

**Comment by plocket** [comment] 2020-05-15 19:42
How do we find out that it doesn't work for most people? How do we assess that?

**Comment by plocket** [comment] 2020-05-15 19:46
Welp, I guess if it works for any number of people, that's better than none.

**Comment by nonprofittechy** [comment] 2020-05-15 20:06
If you are doing these tests yourself, try same feature in GBLS.org/made on a device that doesn't work on our form.

**Comment by nonprofittechy** [comment] 2020-07-01 03:35
As this is an upstream issue without a replication, closing for now. Did flag some usability suggestions for Jonathan on Slack related to this recently.

**Closed as completed by nonprofittechy** 2020-07-01 03:35 UTC
Labels: bug
